version: 1.0

snow:
  - id: 545562 # Milo CC

notifications:
  jira:
    default:
      project: MWPW # Mandatory
      filters:
        include:
          risk_rating: R3
        exclude:
          tool_type:
            - "sbom_grype" # Exclude SBOM tickets which duplicate findings already created by snyk
      fields:
        assignee:
          name: sumanh
        customfield_11800: MWPW-164516 #epic link
        customfield_12900: 
          value: Brahmos
        watchers:
          - casalino
          - saljain
          - mathuria
          - dstrong
        labels:
          - "OriginatingProcess=Kodiak"
          - "security"
          - "kodiak-ticket"
        components:
          - name: "DevOps Security" 
